### ISSUE TITLE
Verify that entries are not duplicated

### ISSUE THREAD

**Issue by galargh** [protocol/github-mgmt-template#50]
Right now, a config like this will be accepted without raising an error:
```
members:
  admin:
    - galargh
  member:
    - galargh
```

The resulting application would give `galargh` only `member` permission in the org because that group was defined last.

We should disallow same entries being present in multiple groups.
